config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :car_models, only: %i[show new create edit index update]
  resources :subsidiaries, only: %i[show new create edit index update] do
    member do
      get 'rental_price', to: 'rental_prices#new'
      post 'rental_price', to: 'rental_prices#create'
    end
  end
  resources :cars, only: %i[show new create edit update index]
  resources :manufactures, only: %i[new create show edit update index]
  resources :rental_prices, only: %i[index]
  resources :fuel_type, only: %i[show new create]
  resources :clients, only: %i[show new create]
  resources :individual_clients, only: %i[show new create index edit update]
  resources :corporate_clients, only: %i[show new create index edit update]
  resources :categories, only: %i[index show new create edit update]
  resources :rentals, only: %i[index new create show] do
    get 'search', on: :collection
    member do
      get 'review'
      post 'confirm'
      post 'start'
      get 'closure_review'
      post 'finalize'
    end
  end
  resources :addons, only: %i[index new create edit update]
  resources :addon_prices, only: %i[index new create]

  namespace 'api' do
    namespace 'v1' do
      resources :cars, only: %i[show index create update destroy]
    end
  end
end

app/views/shared/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Rental Cars', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
                                               data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                                                                     aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <li class="nav-item">
            <%= link_to 'Modelos', car_models_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Categorias', categories_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Filiais', subsidiaries_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Fabricantes', manufactures_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Configurar preços de locações', rental_prices_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Adicionais de locação', addons_path, class: 'nav-link' %>
          </li>
        <% elsif current_user.user? %>
          <li class="nav-item">
            <%= link_to 'Carros', cars_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Preços de locações', rental_prices_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Preços de adicionais', addon_prices_path, class: 'nav-link' %>
          </li>
          <%= link_to 'Clientes individuais', individual_clients_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Clientes corporativos', corporate_clients_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Locações', rentals_path, class: 'nav-link' %>
          </li>
        <% end %>
      <% end %>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item d-flex align-items-center mr-sm-2">
          <strong><%= current_user.email %></strong>
        </li>
        <li class="nav-item">
          <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'btn btn-outline-primary' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Entrar', new_user_session_path, class: 'btn btn-outline-primary' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>