config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :car_models, only: %i[show new create edit index update]
  resources :subsidiaries, only: %i[show new create edit index update] do
    member do
      get 'rental_price', to: 'rental_prices#new'
      post 'rental_price', to: 'rental_prices#create'
    end
  end
  resources :cars, only: %i[show new create edit update index]
  resources :manufactures, only: %i[new create show edit update index]
  resources :rental_prices, only: %i[index]
  resources :fuel_type, only: %i[show new create]
  resources :clients, only: %i[show new create]
  resources :individual_clients, only: %i[show new create index edit update]
  resources :corporate_clients, only: %i[show new create index edit update]
  resources :categories, only: %i[index show new create edit update]
  resources :rentals, only: %i[index new create show] do
    get 'search', on: :collection
    member do
      get 'review'
      post 'confirm'
      post 'start'
      get 'closure_review'
      post 'finalize'
    end
  end
  resources :addons, only: %i[index new create edit update]
  resources :addon_prices, only: %i[index new create]

  namespace 'api' do
    namespace 'v1' do
      resources :cars, only: %i[show index create update destroy]
    end
  end
end

app/models/rental.rb
class Rental < ApplicationRecord
  before_create :generate_reservation_code
  enum status: { scheduled: 0, in_review: 5, ongoing: 10, finalized: 15 }
  has_many :rental_items
  belongs_to :client
  belongs_to :category
  belongs_to :subsidiary
  validates :start_date, :end_date, presence: true
  validate :price_cannot_be_zero, :rental_period_must_be_valid
  validate :cars_available, on: :create

  accepts_nested_attributes_for :rental_items

  def calculate_price_projection
    return 0 unless start_date && end_date && category

    days = (end_date - start_date).to_i
    value = category.daily_rate + category.car_insurance +
            category.third_party_insurance
    days * value
  end

  def rental_period_must_be_valid
    return 0 if start_date.nil? || end_date.nil?

    if start_date < Time.zone.now
      errors.add(:start_date, 'não pode estar no passado.')
    elsif start_date > end_date
      errors.add(:start_date, 'não pode ser maior que data de término.')
    end
  end

  def available_cars
    category.cars.where(status: :available, subsidiary: subsidiary)
  end

  def cars_available
    if cars_available_at_date_range
      errors.add(:category, 'Não há carros disponíveis na categoria escolhida.')
    end
  end

  def price_cannot_be_zero
    if calculate_price_projection <= 0
      errors.add(:base, 'Valor estimado não pode ser zero.')
    end
  end

  def car
    rental_items.find_by(rentable_type: 'Car').rentable
  end

  def user_authorized(user)
    return true if user.admin?

    subsidiary == user.subsidiary
  end

  private

  def cars_available_at_date_range
    scheduled_rentals = Rental.where(category: category)
                              .where(start_date: start_date..end_date)
                              .or(Rental.where(category: category)
      .where(end_date: start_date..end_date))

    available_cars_at_category = Car
                                 .where(status: :available,
                                        subsidiary: subsidiary)
                                 .joins(:car_model)
                                 .where(car_models: { category: category })
    scheduled_rentals.count >= available_cars_at_category.count
  end

  def generate_reservation_code
    self.reservation_code = loop do
      token = generate_random_token
      break token unless Rental.exists?(reservation_code: token)
    end
  end

  def generate_random_token
    charset = Array('A'..'Z') + Array(0..9)
    Array.new(6) { charset.sample }.join
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :authorize_user!, only: %i[confirm]
  before_action :set_rental!, only: %i[confirm show closure_review finalize
                                       start review]

  def index
    @rentals = Rental.where(subsidiary: current_subsidiary)
  end

  def new
    @rental = Rental.new
    @clients = Client.all
    @categories = Category.all
  end

  def create
    @rental = Rental.new(rental_params)
    subsidiary = current_subsidiary
    @rental.subsidiary = subsidiary
    @rental.status = :scheduled
    return redirect_to rental_path(@rental.id) if @rental.save

    @clients = Client.all
    @categories = Category.all
    render :new
  end

  def confirm
    return redirect_to @rental unless @rental.in_review?

    if @car = Car.find_by(id: params[:car_id])
      build_car(@car.id, @rental.id, params[:addon_ids])
      render :confirm
    else
      flash[:danger] = 'Carro deve ser selecionado'
      @cars = @rental.available_cars
      @addons = Addon.joins(:addon_items)
                     .where(addon_items: { status: :available }).group(:id)
      render :review
    end
  end

  def show; end

  def search
    @rental = Rental.find_by(reservation_code: params[:q])
    return redirect_to @rental if @rental

    @rentals = Rental.where(subsidiary: current_subsidiary)
    flash[:danger] = 'Nenhuma locação encontrada'
    render :index
  end

  def review
    if @rental.scheduled?
      @rental.in_review!
      @cars = @rental.available_cars.where(subsidiary: current_subsidiary)
      @addons = Addon.joins(:addon_items)
                     .where(addon_items: { status: :available }).group(:id)
    elsif @rental.ongoing?
      redirect_to closure_review_rental_path(@rental)
    end
  end

  def closure_review
    redirect_to @rental unless @rental.ongoing?
  end

  def start
    return redirect_to @rental unless @rental.in_review?

    @rental.ongoing!
    redirect_to @rental
  end

  private

  def build_car(car_id, rental_id, addons_ids = [])
    car = Car.find_by(id: car_id)
    car.unavailable!
    rental = Rental.find_by(id: rental_id)
    rental.rental_items.create(rentable: car, daily_rate:
                               car.category.daily_rate +
                               car.category.third_party_insurance +
                               car.category.car_insurance)
    if addons = Addon.where(id: addons_ids)
      addon_items = addons.map(&:first_available_item)
      addon_items.each do |addon_item|
        addon_item.unavailable!
        rental.rental_items.create(rentable: addon_item,
                                   daily_rate: addon_item
                                   .current_price(current_subsidiary))
      end
    end
  end

  def rental_params
    params.require(:rental).permit(:category_id, :client_id, :start_date,
                                   :end_date,
                                   rental_items_attributes: [:car_id])
  end

  def set_rental!
    @rental = Rental.find(params[:id])
  end

  def authorize_user!
    @rental = Rental.find(params[:id])
    unless current_user.admin? || @rental.subsidiary == current_subsidiary
      redirect_to @rental
    end
  end
end

app/views/rentals/_rental_information.html.erb
<h1>Locação de:  <%= rental.client.name %></h1>
<h3>Status: 
  <% if rental.scheduled? %>
    <span class="badge badge-info"><%= t(rental.status)%></span>
  <% elsif rental.in_review? %>
    <span class="badge badge-primary"><%= t(rental.status)%></span>
  <% elsif rental.ongoing? %>
    <span class="badge badge-success"><%= t(rental.status)%></span>
  <% elsif rental.finalized? %>
    <span class="badge badge-danger"><%= t(rental.status)%></span>
  <% end %>
</h3>

<dl class='row'>
  <dt class='col-sm-3'><%= Rental.human_attribute_name('reservation_code') %>:</dt>
  <dd class='col-sm-9'><%= rental.reservation_code %></dd>

  <dt class='col-sm-3'><%= Client.human_attribute_name('email') %>:</dt>
  <dd class='col-sm-9'><%= rental.client.email %></dd>

  <dt class='col-sm-3'>CPF/CNPJ:</dt>
  <dd class='col-sm-9'><%= rental.client.cpf %></dd>

  <dt class='col-sm-3'><%= Rental.human_attribute_name('start_date') %>:</dt>
  <dd class='col-sm-9'><%= l rental.start_date, format: :long %></dd>

  <dt class='col-sm-3'><%= Rental.human_attribute_name('end_date') %>:</dt>
  <dd class='col-sm-9'><%= l rental.end_date, format: :long  %></dd>

  <dt class='col-sm-3'><%= Rental.human_attribute_name('subsidiary') %>:</dt>
  <dd class='col-sm-9'><%= rental.subsidiary.name %></dd>

  <dt class='col-sm-3'><%= Rental.human_attribute_name('category') %>:</dt>
  <dd class='col-sm-9'><%= rental.category.name  %></dd>

  <dt class='col-sm-3'><%= Rental.human_attribute_name('price_projection') %>:</dt>
  <dd class='col-sm-9'><%= number_to_currency(rental.calculate_price_projection) %></dd>
</dl>

app/views/rentals/closure_review.html.erb
<h1>Finalizar locação</h1>
<%= render partial: 'rental_information', locals: { rental: @rental } %>
<dl class='row'>
<% @rental.rental_items.each do |rental_item| %>
  <% if !rental_item.car? %>
    <dt class='col-sm-3'><%= rental_item.rentable.addon.name %>:</dt>
    <dd class='col-sm-9'> n <%= rental_item.rentable.registration_number  %></dd>
  <% end %>
<% end %>
</dl>
<h2>Preço final: <%= number_to_currency(@rental.calculate_final_price) %></h2>
<dl class='row'>
  <dt class='col-sm-3'><%= Car.human_attribute_name('license_plate') %>:</dt>
  <dd class='col-sm-9'><%= @rental.car.license_plate %></dd>
</dl>
<% if @rental.ongoing? %>
  <%= link_to 'Finalizar locação', finalize_rental_path, method: :post, class: 'btn btn-danger' %>
<% end %>

app/views/rentals/confirm.html.erb
<h1>Confirmar dados da locação</h1>
<%= render partial: 'rental_information', locals: { rental: @rental } %>
<dl class='row'>
  <dt class='col-sm-3'><%= Car.human_attribute_name('license_plate') %>:</dt>
  <dd class='col-sm-9'><%= @car.license_plate %></dd>
  <% @rental.rental_items.each do |rental_item| %>
    <% if !rental_item.car? %>
      <dt class='col-sm-3'><%= rental_item.rentable.addon.name %>:</dt>
      <dd class='col-sm-9'> n <%= rental_item.rentable.registration_number  %></dd>
    <% end %>
  <% end %>
</dl>
<% if @rental.in_review? %>
  <%= link_to 'Confirmar', start_rental_path, method: :post, class: 'btn btn-success' %>
<% end %>

app/views/rentals/index.html.erb
<h1>Locações</h1>
<%= link_to 'Agendar locação', new_rental_path, class: 'btn btn-primary mt-1 mb-1' %>
<%= form_with(url: search_rentals_path, method: :get, data: {remote: false}, class: 'mb-1 mt-1') do |f| %>
  <%= f.label(:q, 'Código da reserva:') %>
  <%= f.text_field(:q)  %>
  <%= f.submit 'Buscar' %>
<% end %>
<table class='table table-striped mt-1 mb-1'>
  <thead class='thead-dark'>
    <tr>
      <th scope="col"><%= Client.model_name.human %></th>
      <th scope="col"><%= Rental.human_attribute_name('status') %></th>
      <th scope="col"><%= Rental.human_attribute_name('start_date') %></th>
      <th scope="col"><%= Rental.human_attribute_name('end_date') %></th>
      <th scope="col"><%= Rental.human_attribute_name('category')%></th>
      <th scope="col"><%= Rental.human_attribute_name('price_projection')%></th>
    </tr>
  </thead>
  <tbody>
      <% @rentals.each do |rental| %>
      <tr>
        <td><%= link_to rental.client.name, rental_path(rental.id) %></td>
        <td>
          <% if rental.scheduled? %>
            <span class="badge badge-info"><%= t(rental.status)%></span>
          <% elsif rental.in_review? %>
            <span class="badge badge-primary"><%= t(rental.status)%></span>
          <% elsif rental.ongoing? %>
            <span class="badge badge-success"><%= t(rental.status)%></span>
          <% elsif rental.finalized? %>
            <span class="badge badge-danger"><%= t(rental.status)%></span>
          <% end %>
        </td>
        <td><%= l(rental.start_date, format: :long) %></td>
        <td><%= l(rental.end_date, format: :long) %></td>
        <td><%= rental.category.name %></td>
        <td><%= number_to_currency(rental.calculate_price_projection) %></td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/rentals/new.html.erb
<h1>Nova locação</h1>
<% if @rental.errors.any? %>
  <div class='alert alert-danger'>
    <ul>
      <% @rental.errors.full_messages.each do |message| %>
        <li><%= message  %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @rental do |f| %>
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1"><%= Rental.human_attribute_name('start_date') %></span>
  </div>
  <%= f.date_field(:start_date, class: 'start_date form-control', describedby:'basic-addon1') %>
</div>
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon2"><%= Rental.human_attribute_name('end_date') %></span>
  </div>
  <%= f.date_field(:end_date, class: 'end_date form-control', describedby:'basic-addon2') %>
</div>
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <label class="input-group-text" for="inputGroupSelect01"><%= Rental.human_attribute_name('client') %></label>
  </div>
  <%= f.collection_select(:client_id, @clients, :id, :client_description, {}, { class: "custom-select", id: "inputGroupSelect01" }) %>
</div>
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <label class="input-group-text" for="inputGroupSelect02"><%= Rental.human_attribute_name('category') %></label>
  </div>
  <%= f.collection_select(:category_id, @categories, :id, :name, {}, { class: "custom-select", id: "inputGroupSelect02" }) %>
</div>
  <%= f.submit 'Agendar' %>
<% end %>

app/views/rentals/review.html.erb
<h1>Revisão da locação</h1>

<%= render partial: 'rental_information', locals: { rental: @rental } %>

<% if current_user.admin? || @rental.subsidiary == current_user.subsidiary %>
  <ul>
    <%= form_with url: confirm_rental_path, method: :post, data: { remote: false } do |f| %>
      <h3>Carros</h3>
      <div class="cards">
        <%= f.collection_radio_buttons(:car_id, @cars, :id, :license_plate) do |r| %>
          <div class="card" style="width: 18rem;">
            <h5 class="card-title text-center"><%= r.label{ r.radio_button(id: r.object.license_plate) } %></h5>
            <% if r.object.car_model.photo.attached?  %>
              <%= image_tag r.object.car_model.photo, class: 'card-img-top' %>
            <% end %>
            <div class="card-body">
              <ul>
                <li class="card-text"><%= r.object.license_plate %></li>
                <li class="card-text"><%= r.object.car_model.name %></li>
                <li class="card-text"><%= r.object.car_model.manufacture.name %></li>
                <li class="card-text"><%= r.object.color %></li>
                <li class="card-text"><%= r.object.category.daily_rate %></li>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
      <h3>Acessórios</h3>
      <div class="cards">
        <%= f.collection_check_boxes(:addon_ids, @addons, :id, :name, include_hidden: false) do |c| %>
          <div class="card" style="width: 25rem;">
            <div class="media">
              <div class='align-self-center ml-1 mt-2'><%= c.label{ c.check_box(id: c.object.id) } %></div>
              <% if c.object.photo.attached? %>
                <%= image_tag c.object.photo, class:'mr-3 ml-3 mt-1 mb-1 align-self-center', width:64, height:64 %>
              <% end %>
              <div class="media-body">
                <h5 class="mt-1">  <%= c.text %></h5>
                <p><%= c.object.description %> </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <%= f.submit 'Iniciar locação', class: 'btn btn-primary' %>
    <% end %>
  </ul>
<% end %>

app/views/rentals/show.html.erb
<%= render partial: 'rental_information', locals: { rental: @rental } %>
<% if current_user.admin? || current_user.subsidiary == @rental.subsidiary %>
  <p>
  <% if @rental.scheduled? %>
    <%= link_to 'Iniciar locação', review_rental_path(@rental), class: 'btn btn-primary' %>
  <% elsif @rental.in_review? %>
    <%= link_to 'Continuar locação', review_rental_path(@rental), class: 'btn btn-secondary' %>
  <% elsif @rental.finalized? && current_user.admin? %>
    <%= link_to 'Reportar problema', report_rental_path(@rental), class: 'btn btn-warning' %>
  <% end %>
  </p>
<% end %>