config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :car_models, only: %i[show new create edit index update]
  resources :subsidiaries, only: %i[show new create edit index update] do
    member do
      get 'rental_price', to: 'rental_prices#new'
      post 'rental_price', to: 'rental_prices#create'
    end
  end
  resources :cars, only: %i[show new create edit update index]
  resources :manufactures, only: %i[new create show edit update index]
  resources :rental_prices, only: %i[index]
  resources :fuel_type, only: %i[show new create]
  resources :clients, only: %i[show new create]
  resources :individual_clients, only: %i[show new create index edit update]
  resources :corporate_clients, only: %i[show new create index edit update]
  resources :categories, only: %i[index show new create edit update]
  resources :rentals, only: %i[index new create show] do
    get 'search', on: :collection
    member do
      get 'review'
      post 'confirm'
      post 'start'
      get 'closure_review'
      post 'finalize'
    end
  end
  resources :addons, only: %i[index new create edit update]
  resources :addon_prices, only: %i[index new create]

  namespace 'api' do
    namespace 'v1' do
      resources :cars, only: %i[show index create update destroy]
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :daily_rate, :car_insurance,
            :third_party_insurance, presence: true
  has_many :rental_prices
  has_many :car_models
  has_many :cars, through: :car_models
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authorize_admin
  before_action :find_category, only: [:show, :edit, :update]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end
  
  def edit
  end

  def update
    @category.update(category_params)
    redirect_to @category
    flash[:notice]= 'Categoria editada com sucesso!'

  end

  def create
    @category = Category.new(category_params)
    @category.save
    redirect_to @category
    flash[:notice]= 'Categoria cadastrada com sucesso!'

  end
  private

  def find_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :daily_rate, :car_insurance,
                                     :third_party_insurance)
  end
end

app/views/categories/edit.html.erb
<%= form_for @category do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name%>  

  <%= f.label :daily_rate %>
  <%= f.number_field :daily_rate %> 

  <%= f.label :car_insurance %>
  <%= f.number_field :car_insurance %> 

  <%= f.label :third_party_insurance %>
  <%= f.number_field :third_party_insurance %>

  <%= f.submit 'Enviar'%>
<% end %>

app/views/categories/index.html.erb
<h1>Categorias de locação</h1>

<%= link_to 'Nova Categoria', new_category_path%>

<% if @categories.any? %>
<table class='table table-striped mt-1 mb-1'>
  <thead class='thead-dark'>
    <tr>
      <th scope="col"><%= Category.model_name.human %></th>
      <th scope="col"><%= Category.human_attribute_name('daily_rate') %></th>
      <th scope="col"><%= Category.human_attribute_name('car_insurance') %></th>
      <th scope="col"><%= Category.human_attribute_name('third_party_insurance') %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category_path(category) %></td>
        <td><%= number_to_currency(category.daily_rate) %></td>
        <td><%= number_to_currency(category.car_insurance) %></td>
        <td><%= number_to_currency(category.third_party_insurance) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/categories/new.html.erb
<%= form_for @category do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name%>  

  <%= f.label :daily_rate %>
  <%= f.number_field :daily_rate %> 

  <%= f.label :car_insurance %>
  <%= f.number_field :car_insurance %> 

  <%= f.label :third_party_insurance %>
  <%= f.number_field :third_party_insurance %>

  <%= f.submit 'Enviar'%>
<% end %>

app/views/categories/show.html.erb
<h1> Categoria: <%= @category.name%> </h1>

<dt>
  <dd>Nome: <%= @category.name %></dd>
  <dd>Diária padrão: <%= number_to_currency(@category.daily_rate)%></dd>
  <dd>Seguro padrão do carro: <%= number_to_currency(@category.car_insurance)%></dd>
  <dd>Seguro padrão contra terceiros: <%= number_to_currency(@category.third_party_insurance)%></dd>
</dt>

<%= link_to 'Voltar', categories_path %>
<%= link_to 'Editar', edit_category_path(@category) %>