config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :car_models, only: %i[show new create edit index update]
  resources :subsidiaries, only: %i[show new create edit index update] do
    member do
      get 'rental_price', to: 'rental_prices#new'
      post 'rental_price', to: 'rental_prices#create'
    end
  end
  resources :cars, only: %i[show new create edit update index]
  resources :manufactures, only: %i[new create show edit update index]
  resources :rental_prices, only: %i[index]
  resources :fuel_type, only: %i[show new create]
  resources :clients, only: %i[show new create]
  resources :individual_clients, only: %i[show new create index edit update]
  resources :corporate_clients, only: %i[show new create index edit update]
  resources :categories, only: %i[index show new create edit update]
  resources :rentals, only: %i[index new create show] do
    get 'search', on: :collection
    member do
      get 'review'
      post 'confirm'
      post 'start'
      get 'closure_review'
      post 'finalize'
    end
  end
  resources :addons, only: %i[index new create edit update]
  resources :addon_prices, only: %i[index new create]

  namespace 'api' do
    namespace 'v1' do
      resources :cars, only: %i[show index create update destroy]
    end
  end
end

app/models/car.rb
class Car < ApplicationRecord
  enum status: { available: 0, unavailable: 10, pending_inspection: 20 }
  belongs_to :car_model
  belongs_to :subsidiary
  has_one :category, through: :car_model
  validates :car_km, presence: true
  validates :color, presence: true
  validates :license_plate, presence: true
  validates :license_plate, uniqueness: true
  has_one_attached :photo

 
end

app/controllers/api/v1/cars_controller.rb
class Api::V1::CarsController < Api::V1::ApiController
  def show
    @car = Car.find(params[:id])
    @photo = url_for(@car.photo)
    render json: {car: @car, photo: @photo}
  end
  
  def index
    @cars = Car.all
    unless @cars.empty?
      render json: @cars
    else
      render json: {message: 'No records found'}, status: :not_found
    end
  end

  def create
    @car = Car.new(car_params)
    
    if @car.valid?
      #photo_path = params.permit(:photo)["photo"]
      #@car.photo.attach(io: File.open(photo_path), filename: photo_path.split('/')[-1])
      @car.save!
      render json: {message: 'Created successfully'}, status: :created 
    else
      render json: {Validation_failure: @car.errors.full_messages}, status: :precondition_failed
    end
  end
  
  def update 
    @car = Car.find(params[:id])
    @car.update(car_params)
    
      render json: {message: 'Updated successfully'}, status: :ok
  end

  def destroy
    @car = Car.find(params[:id])
    @car.delete
    render json: {message: 'Deleted successfully'}, status: :ok
  end

  private

  def car_params
    params.permit(:car_km, :license_plate, :color,
                                :subsidiary_id, :car_model_id)
  end

  
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authorize_user!, only: %i[edit update show]

  def index
    @cars = Car.where(subsidiary: current_subsidiary)
  end

  def new
    @car = Car.new
    @car_models = CarModel.all
  end

  def create
    @car = Car.new(car_params)
    @car.subsidiary = current_subsidiary
    return redirect_to @car if @car.save

    @car_models = CarModel.all
    render :new
  end

  def show
    @car = Car.find(params[:id])
  end

  def edit
    @car = Car.find(params[:id])
    @car_models = CarModel.all
  end

  def update
    @car = Car.find(params[:id])
    return redirect_to @car if @car.update(car_params)

    @car_models = CarModel.all
    render :edit
  end

  private

  def car_params
    params.require(:car).permit(%i[car_model_id car_km color license_plate])
  end

  def authorize_user!
    unless Car.find(params[:id]).subsidiary == current_subsidiary
      redirect_to cars_path
    end
  end
end

app/views/cars/_form.html.erb
<% if car.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for car do |f| %>
  <div class="form-group">
    <%= f.label :car_model_id %>
    <%= f.collection_select :car_model_id, @car_models, :id, :name, {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :car_km %>
    <%= f.text_field :car_km, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :color %>
    <%= f.text_field :color, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :license_plate %>
    <%= f.text_field :license_plate, class: 'form-control' %>
  </div>
  <%= f.submit 'Enviar', class: 'btn btn-primary' %>
<% end %>

app/views/cars/edit.html.erb
<h1>Editar carro</h1>

<%= render partial: 'form', locals: { car: @car, car_models: @car_models } %>

app/views/cars/index.html.erb
<h1>Carros</h1>
<%= link_to 'Registrar novo carro', new_car_path, class: 'btn btn-primary mb-1 mt-1' %>
<% if @cars.any? %>
  <table class='table table-striped mt-1 mb-1'>
    <thead class='thead-dark'>
      <tr>
        <th scope='col'><%= Car.human_attribute_name('license_plate') %>: </th>
        <th scope='col'><%= Car.human_attribute_name('car_model') %>: </th>
        <th scope='col'><%= Car.human_attribute_name('color') %>: </th>
        <th scope='col'><%= Category.model_name.human %>: </th>
        <th scope='col'><%= Car.human_attribute_name('status') %>: </th>
      </tr>
    </thead>
    <tbody>
      <% @cars.each do |car| %>
        <tr>
          <td><%= link_to car.license_plate, car_path(car) %></td>
          <td><%= car.car_model.name %></td>
          <td><%= car.color %></td>
          <td><%= car.car_model.category.name %></td>
          <td>
            <% if car.available? %>
              <span class='badge badge-success'><%= t(car.status) %></span>
            <% elsif car.unavailable? %>
              <span class='badge badge-danger'><%= t(car.status) %></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/cars/new.html.erb
<h1>Novo carro</h1>

<%= render partial: 'form', locals: { car: @car, car_models: @car_models } %>

app/views/cars/show.html.erb
<dl class="row">
  <dt class="col-sm-3"><%= CarModel.model_name.human %></dt>
  <dd class="col-sm-9"><%= @car.car_model.name %></dd>

  <dt class="col-sm-3"><%= Manufacture.model_name.human %></dt>
  <dd class="col-sm-9"><%= @car.car_model.manufacture.name %></dd>

  <dt class="col-sm-3"><%= FuelType.model_name.human%></dt>
  <dd class="col-sm-9"><%= @car.car_model.fuel_type.name %></dd>

  <dt class="col-sm-3"><%= Car.human_attribute_name('car_km') %></dt>
  <dd class="col-sm-9"><%= @car.car_km %></dd>

  <dt class="col-sm-3"><%= Car.human_attribute_name('color') %></dt>
  <dd class="col-sm-9"><%= @car.color %></dd>
  
  <dt class="col-sm-3"><%= Car.human_attribute_name('license_plate') %></dt>
  <dd class="col-sm-9"><%= @car.license_plate %></dd>
</dl>

<%= link_to 'Editar carro', edit_car_path, class: 'btn btn-primary' %>